name: Build Docker image for ARM64

on:
  push:
    branches:
      - main  # 触发代码推送至 main 分支时
  pull_request:  # 在拉取请求时执行
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for ARM64
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true  # 如果你想将镜像推送至 Docker Hub 或其他容器注册中心
          tags: your-dockerhub-username/your-image-name:latest # 修改为你的 Docker Hub 用户名和镜像名

      - name: Clean up
        run: docker system prune -af
